#ifndef DROP_VERSION_HPP
#define DROP_VERSION_HPP

#define DROP_VERSION "@DROP_VERSION@"
#define DROP_COMMIT_HASH "@DROP_COMMIT_HASH@"
#define DROP_TAG "@DROP_TAG@"
#define DROP_REMOTE "@DROP_REMOTE@"

#endif /* DROP_VERSION_HPP */
